added condition to fail a pr after sonar

diff --git a/.github/workflows/pr_action.yml b/.github/workflows/pr_action.yml
--- a/.github/workflows/pr_action.yml
+++ b/.github/workflows/pr_action.yml
@@ -57,8 +57,9 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=muslugorkem_sm703-term-project
-
+        run: >
+          mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=muslugorkem_sm703-term-project || 
+          (echo 'SonarCloud analysis failed'; exit 1)
 
       # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
       # - name: Update dependency graph
